### This is an ipython script to show that it can be executed in ipython notebook, ipython command line and python command line

### Notes: 
It is better not use ipython-specific commands here. 

So that the file can be exported to a python script,
and then it can be executed with either python or ipython.

In [2]:
print ("hello world!")

hello world!


In [4]:
import numpy as np

array1 = np.matrix( [ [1,2,3], [4,5,6]  ]  )
array2 = np.matrix( [ [10, 20], [30, 40], [50, 60] ] )

print ("array1 =\n", array1)
print ("array2 =\n", array2)

array1 =
 [[1 2 3]
 [4 5 6]]
array2 =
 [[10 20]
 [30 40]
 [50 60]]


In [14]:
# try plotting package
import matplotlib.pyplot as plt

xstart = 0
xend = 6
datalength = 100
x=np.linspace(xstart, xend, datalength)
y1=np.sin(x)
y2 = np.random.normal(scale=1, size=datalength)

image1 = plt.plot(x,y1)
plt.savefig('/tmp/image1.png')
#plt.show()

# without clearing image1, image2 will be overlayed on top of image1
image2 = plt.plot(x,y2)

# save the image in a certain location
plt.savefig('/tmp/image2.png')

# display the image
plt.show()

In [ ]:
# try the pandas package, which runs on top of numpy
import pandas as pd

